site_name: My Docs

nav:
  - Home: index.md
  - Math: 
      - Math/分析/分析.md
      - Math/代数/代数.md
      - Math/几何/几何.md
      - Math/数论/数论.md
  - Computer:
      - 系统软件:
            - Computer/系统软件/系统软件.md
            - 分布式系统:
                  - Computer/系统软件/分布式系统/分布式系统.md
                  - 分布式计算平台:
                        - Computer/系统软件/分布式系统/分布式计算平台/分布式计算平台.md 
                        - Hadoop:
                              - Computer/系统软件/分布式系统/分布式计算平台/Hadoop/Hadoop.md
                              - Computer/系统软件/分布式系统/分布式计算平台/Hadoop/Zookeeper.md
                              - Computer/系统软件/分布式系统/分布式计算平台/Hadoop/Hbase.md
      - 程序设计: 
            - Python: 
                  - Computer/程序设计/Python/Python.md
                  - 基础语法:
                        - Computer/程序设计/Python/基础语法/基础语法.md
                  - 第三方库:
                        - Computer/程序设计/Python/第三方库/第三方库.md
                        - Computer/程序设计/Python/第三方库/Django.md
            - Java: 
                  - Computer/程序设计/Java.md
      - 程序软件: 
            - git:  Computer/程序软件/git.md
            - docker: Computer/程序软件/docker.md
      - 计算机网络:
            - 计算机网络: Computer/计算机网络/计算机网络.md
            - 网络安全: Computer/计算机网络/网络安全.md
      # - 数据库: Computer/



theme:
    icon:
        logo: material/home
    name: material
    language: zh
    palette:
        # 切换到亮色
        - media: "(prefers-color-scheme: light)" # 根据系统的颜色模式自动切换
          scheme: default
          primary: pink
          accent: pink
          toggle:
              icon: material/weather-night
              name: 切换到暗色模式

        # 切换到暗色
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: pink
          accent: pink
          toggle:
              icon: material/weather-sunny
              name: 切换到亮色模式
    features:
        - navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
        - navigation.tabs # 页面上方的标签页
        - navigation.tracking # 页面滚动时，导航栏高亮当前页面
      #   - navigation.sections # 使导航栏分块
        - navigation.expand # 默认展开导航
        - navigation.prune # 只渲染当前页面的导航
        - toc.follow # 滚动的时候侧边栏自动跟随
        - navigation.top # 返回顶部按钮
        - search.suggest # 补全建议
        - search.highlight # 搜索结果高亮
        - search.share # 搜索结果分享
        - navigation.footer # 页脚提示下一章
        - content.code.copy # 代码段上的赋值按钮

markdown_extensions:
    - admonition # 警告语法
    - def_list
    - footnotes
    - abbr
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html
    - pymdownx.arithmatex: # latex支持
          generic: true
    - toc:
          permalink: true # 固定标题位置为当前位置
          toc_depth: 5 # 目录深度
    - pymdownx.highlight: # 代码块高亮
          anchor_linenums: true
          linenums: true # 显示行号
          use_pygments: true # 代码高亮
          pygments_lang_class: true
          auto_title: true # 显示编程语言名称
          linenums_style: pymdownx-inline # 行号样式,防止复制的时候复制行号
    - pymdownx.betterem # 强调美化,比如**text**会被美化
    - pymdownx.caret # 上标和下标
    - pymdownx.mark # 上标和下标
    - pymdownx.tilde # 上标和下标
    - pymdownx.keys # 显示按键组合
    - pymdownx.critic
    - pymdownx.details # 可以折叠的代码块 ??? note 可以让警告变成折叠的
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.magiclink # 自动识别链接
    - pymdownx.smartsymbols # 智能符号
    - pymdownx.snippets # 代码段
    - pymdownx.tasklist:
          custom_checkbox: true # 自定义复选框
    - attr_list
    # - pymdownx.emoji:
          # emoji_index: !!python/name:material.extensions.emoji.twemoji
          # emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences: # 代码块中支持Mermaid
          custom_fences: # 支持 Mermaid
              - name: mermaid
                class: mermaid
                # format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - meta # 支持Markdown文件上方自定义标题标签等
    - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 下面的是需要自定义的内容，请不要修改上方的内容，上面都是在开启各种插件和功能

copyright: Copyright &copy; # Python调包侠 # 左下角的版权声明



# plugins:
#     - mkdocstrings:
#           handlers:
#               python:
#                   paths: [src]
#     - search # 搜索插件
#     # - offline # 离线本地搜索，和navigation.instant不能同时启用

extra:
    # generator: false  #删除页脚显示“使用 MkDocs 材料制造”
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/zyssnh
          name: GitHub
        - icon: fontawesome/brands/bilibili
          link: https://space.bilibili.com/485628053
          name: Bilibili
      #   - icon: material/email
      #     link: Python调包侠:<271374667@qq.com>
      #     name: Email

